#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Word Document Export Feature
# Spec: 001-word-document-export

set -e

echo "========================================"
echo "InkPot Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_DIR="/Users/gustavogomez/projects/InkPot/InkPot"

# Navigate to project directory
cd "$PROJECT_DIR"

# Function to wait for service
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# DEPENDENCY CHECK
# ============================================

echo ""
echo "📦 Checking dependencies..."

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# Check if docx package is installed
if ! npm ls docx 2>/dev/null | grep -q "docx@"; then
    echo -e "${YELLOW}Installing docx package...${NC}"
    npm install docx
fi

echo -e "${GREEN}Dependencies ready${NC}"

# ============================================
# DATABASE CHECK
# ============================================

echo ""
echo "🗄️  Checking database..."

# Run prisma generate if needed
if [ ! -d "src/main/database/generated" ]; then
    echo -e "${YELLOW}Generating Prisma client...${NC}"
    npm run db:generate
fi

echo -e "${GREEN}Database ready${NC}"

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "🚀 Starting development server..."
echo ""

# Start the Electron dev server
npm run dev &
DEV_PID=$!

# Wait for Vite dev server
wait_for_service 3000 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Development Server:  http://localhost:3000"
echo ""
echo "Commands:"
echo "  npm run dev       - Start development server"
echo "  npm test          - Run tests"
echo "  npm run lint      - Run linting"
echo "  npm run build     - Build for production"
echo ""
echo "Feature: Word Document Export"
echo "  - Follow implementation_plan.json for subtask order"
echo "  - Reuse parseMarkdown() from markdown-parser.ts"
echo "  - Follow patterns from pdf-service.ts"
echo ""
echo "Press Ctrl+C to stop the development server"
echo ""

# Keep script running
wait $DEV_PID
