-- AlterTable
ALTER TABLE "Project" ADD COLUMN "hasToc" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Project" ADD COLUMN "tocMinLevel" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Project" ADD COLUMN "tocMaxLevel" INTEGER NOT NULL DEFAULT 3;
